// Rich Prototype Data for CCIS CONNECT
export const rooms = [
  { id: '100A', name: 'Room 100A', x: 15, y: 25, available: true, capacity: 45, floor: 1, type: 'Classroom', equipment: ['Projector', 'Whiteboard', 'AC'], building: 'Main Building' },
  { id: '100B', name: 'Room 100B', x: 35, y: 25, available: false, capacity: 40, floor: 1, type: 'Classroom', equipment: ['Smart TV', 'Whiteboard'], building: 'Main Building' },
  { id: '100C', name: 'Room 100C', x: 55, y: 25, available: true, capacity: 35, floor: 1, type: 'Classroom', equipment: ['Projector', 'AC'], building: 'Main Building' },
  { id: '101A', name: 'CS Lab 1', x: 75, y: 25, available: true, capacity: 50, floor: 1, type: 'Laboratory', equipment: ['40 Computers', 'Projector', 'AC'], building: 'Main Building' },
  { id: '102A', name: 'CS Lab 2', x: 15, y: 50, available: false, capacity: 50, floor: 1, type: 'Laboratory', equipment: ['40 Computers', 'Smart Board'], building: 'Main Building' },
  { id: '103', name: 'Room 103', x: 35, y: 50, available: true, capacity: 30, floor: 1, type: 'Classroom', equipment: ['TV Monitor', 'Whiteboard'], building: 'Main Building' },
  { id: '104', name: 'Networking Lab', x: 55, y: 50, available: true, capacity: 40, floor: 1, type: 'Laboratory', equipment: ['30 Computers', 'Network Equipment'], building: 'Main Building' },
  { id: '105', name: 'Room 105', x: 75, y: 50, available: false, capacity: 45, floor: 1, type: 'Classroom', equipment: ['Projector', 'Sound System'], building: 'Main Building' },
  
  { id: '201', name: 'Faculty Room', x: 25, y: 15, available: true, capacity: 30, floor: 2, type: 'Office', equipment: ['Computers', 'Printer'], building: 'Main Building' },
  { id: '202', name: 'Meeting Room A', x: 45, y: 15, available: true, capacity: 20, floor: 2, type: 'Office', equipment: ['Conference Table', 'TV'], building: 'Main Building' },
  { id: '203', name: 'Meeting Room B', x: 65, y: 15, available: false, capacity: 15, floor: 2, type: 'Office', equipment: ['Whiteboard', 'Projector'], building: 'Main Building' },
  
  { id: '301', name: 'Auditorium', x: 30, y: 35, available: true, capacity: 200, floor: 3, type: 'Lecture Hall', equipment: ['Stage', 'Sound System', 'Projector', 'AC'], building: 'Main Building' },
  { id: '302', name: 'Conference Hall', x: 60, y: 35, available: false, capacity: 100, floor: 3, type: 'Lecture Hall', equipment: ['Sound System', '2 Projectors'], building: 'Main Building' },
];

export const pointsOfInterest = [
  { id: 'dean', name: "Dean's Office", x: 85, y: 65, type: 'Office', description: 'CCIS Dean Office - 2nd Floor' },
  { id: 'library', name: 'Learning Commons', x: 85, y: 45, type: 'Library', description: 'Study Area & Resources' },
  { id: 'techlab', name: 'Innovation Lab', x: 15, y: 75, type: 'Laboratory', description: 'IoT & Hardware Lab' },
  { id: 'lounge', name: 'Student Lounge', x: 45, y: 75, type: 'Facility', description: 'Relaxation Area' },
  { id: 'cafeteria', name: 'Cafeteria', x: 75, y: 75, type: 'Facility', description: 'Food & Beverages' },
  { id: 'entrance', name: 'Main Entrance', x: 10, y: 10, type: 'Facility', description: 'Building Entry Point' },
];

export const equipment = [
  { id: 'eq1', name: 'MacBook Pro', location: 'Learning Commons', available: true, quantity: 15, totalQuantity: 15, category: 'Electronics', specs: '16GB RAM, M1 Chip', image: '💻' },
  { id: 'eq2', name: 'Dell Laptop', location: 'Learning Commons', available: true, quantity: 20, totalQuantity: 25, category: 'Electronics', specs: 'i7, 16GB RAM', image: '💻' },
  { id: 'eq3', name: '4K Projector', location: "Dean's Office", available: true, quantity: 8, totalQuantity: 10, category: 'AV Equipment', specs: 'HDMI, Wireless', image: '📽️' },
  { id: 'eq4', name: 'Portable Projector', location: 'Learning Commons', available: true, quantity: 5, totalQuantity: 6, category: 'AV Equipment', specs: 'Battery-powered', image: '📽️' },
  { id: 'eq5', name: 'iPad Pro', location: 'Learning Commons', available: true, quantity: 12, totalQuantity: 12, category: 'Electronics', specs: '12.9", Apple Pencil', image: '📱' },
  { id: 'eq6', name: 'Android Tablet', location: 'Innovation Lab', available: true, quantity: 10, totalQuantity: 10, category: 'Electronics', specs: 'Samsung Galaxy Tab', image: '📱' },
  { id: 'eq7', name: 'Wireless Microphone', location: "Dean's Office", available: true, quantity: 6, totalQuantity: 8, category: 'AV Equipment', specs: 'UHF, Handheld', image: '🎤' },
  { id: 'eq8', name: 'Lavalier Mic Set', location: 'Innovation Lab', available: true, quantity: 4, totalQuantity: 4, category: 'AV Equipment', specs: 'Clip-on, Wireless', image: '🎤' },
  { id: 'eq9', name: 'DSLR Camera', location: 'Learning Commons', available: true, quantity: 2, totalQuantity: 5, category: 'Electronics', specs: 'Canon EOS, 24MP', image: '📷' },
  { id: 'eq10', name: 'Action Camera', location: 'Innovation Lab', available: true, quantity: 4, totalQuantity: 4, category: 'Electronics', specs: 'GoPro, 4K', image: '📷' },
  { id: 'eq11', name: 'Tripod Stand', location: 'Learning Commons', available: true, quantity: 8, totalQuantity: 8, category: 'Accessories', specs: 'Adjustable height', image: '📐' },
  { id: 'eq12', name: 'Portable Speaker', location: "Dean's Office", available: true, quantity: 10, totalQuantity: 12, category: 'AV Equipment', specs: 'Bluetooth, 50W', image: '🔊' },
  { id: 'eq13', name: 'HDMI Cables', location: 'Learning Commons', available: true, quantity: 25, totalQuantity: 30, category: 'Accessories', specs: '2m, 4K Support', image: '🔌' },
  { id: 'eq14', name: 'USB-C Hub', location: 'Innovation Lab', available: true, quantity: 15, totalQuantity: 15, category: 'Accessories', specs: 'Multi-port adapter', image: '🔌' },
  { id: 'eq15', name: 'Whiteboard Marker Set', location: "Dean's Office", available: true, quantity: 30, totalQuantity: 30, category: 'Supplies', specs: 'Assorted colors', image: '✏️' },
  { id: 'eq16', name: 'Extension Cord', location: 'Learning Commons', available: true, quantity: 20, totalQuantity: 20, category: 'Accessories', specs: '5m, 4 outlets', image: '🔌' },
  
  // Unavailable / Out of Stock Equipment
  { id: 'eq17', name: 'Webcam HD', location: 'Innovation Lab', available: false, quantity: 0, totalQuantity: 6, category: 'Electronics', specs: '1080p, Auto-focus', image: '📹', status: 'All units currently borrowed' },
  { id: 'eq18', name: 'Headphones', location: 'Learning Commons', available: false, quantity: 0, totalQuantity: 20, category: 'Electronics', specs: 'Noise-canceling', image: '🎧', status: 'All units in use' },
  { id: 'eq19', name: 'Drawing Tablet', location: 'Innovation Lab', available: false, quantity: 0, totalQuantity: 5, category: 'Electronics', specs: 'Wacom, Pen included', image: '✍️', status: 'High demand - All borrowed' },
  { id: 'eq20', name: 'Laser Pointer', location: "Dean's Office", available: true, quantity: 12, totalQuantity: 12, category: 'Accessories', specs: 'Wireless presenter', image: '📍' },
  { id: 'eq21', name: 'VR Headset', location: 'Innovation Lab', available: false, quantity: 0, totalQuantity: 3, category: 'Electronics', specs: 'Meta Quest 3', image: '🥽', status: 'Under maintenance' },
  { id: 'eq22', name: 'External SSD', location: 'Learning Commons', available: false, quantity: 0, totalQuantity: 10, category: 'Storage', specs: '1TB, USB 3.2', image: '💾', status: 'All units borrowed' },
  { id: 'eq23', name: 'Ring Light', location: 'Innovation Lab', available: false, quantity: 0, totalQuantity: 4, category: 'AV Equipment', specs: '18" LED', image: '💡', status: 'Maintenance required' },
  { id: 'eq24', name: 'Green Screen', location: 'Innovation Lab', available: false, quantity: 0, totalQuantity: 2, category: 'AV Equipment', specs: 'Portable, 6x9ft', image: '🎬', status: 'Currently in use' },
  { id: 'eq25', name: 'Wireless Mouse', location: 'Learning Commons', available: true, quantity: 18, totalQuantity: 25, category: 'Accessories', specs: 'Bluetooth, Ergonomic', image: '🖱️' },
  { id: 'eq26', name: 'Mechanical Keyboard', location: 'Learning Commons', available: false, quantity: 0, totalQuantity: 8, category: 'Accessories', specs: 'RGB, Cherry MX', image: '⌨️', status: 'All borrowed' },
  { id: 'eq27', name: 'Document Scanner', location: "Dean's Office", available: false, quantity: 0, totalQuantity: 3, category: 'Electronics', specs: 'Portable, USB', image: '🖨️', status: 'Under repair' },
  { id: 'eq28', name: 'Power Bank', location: 'Learning Commons', available: true, quantity: 22, totalQuantity: 30, category: 'Accessories', specs: '20000mAh, Fast charge', image: '🔋' },
];

// Sample users for prototype - stored in localStorage after login
export const prototypeUsers = [
  { 
    idNumber: '2021-00001', 
    password: 'student123', 
    role: 'student', 
    name: 'Juan Dela Cruz', 
    email: 'juan.delacruz@student.example.edu', 
    course: 'BSCS',
    canBorrow: true,
    canUpdateRooms: false
  },
  { 
    idNumber: '2021-00002', 
    password: 'student123', 
    role: 'student', 
    name: 'Maria Santos', 
    email: 'maria.santos@student.example.edu', 
    course: 'BSIT',
    canBorrow: true,
    canUpdateRooms: false
  },
  { 
    idNumber: 'FAC-2020-001', 
    password: 'faculty123', 
    role: 'faculty', 
    name: 'Dr. Robert Chen', 
    email: 'robert.chen@example.edu', 
    department: 'Computer Science',
    canBorrow: true,
    canUpdateRooms: true
  },
  { 
    idNumber: 'FAC-2019-002', 
    password: 'faculty123', 
    role: 'faculty', 
    name: 'Prof. Ana Reyes', 
    email: 'ana.reyes@example.edu', 
    department: 'Information Technology',
    canBorrow: true,
    canUpdateRooms: true
  },
  { 
    idNumber: 'ADM-2018-001', 
    password: 'admin123', 
    role: 'admin', 
    name: 'Dr. Patricia Garcia', 
    email: 'patricia.garcia@example.edu', 
    position: 'CCIS Dean',
    canBorrow: false,
    canUpdateRooms: true
  },
  { 
    idNumber: 'ADM-2018-002', 
    password: 'admin123', 
    role: 'admin', 
    name: 'Mark Wilson', 
    email: 'mark.wilson@example.edu', 
    position: 'Laboratory Manager',
    canBorrow: false,
    canUpdateRooms: true
  },
];

// Sample borrow requests for prototype - covering all scenarios
export const sampleBorrowRequests = [
  // PENDING REQUESTS - waiting for approval
  {
    id: 'REQ-001',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq1',
    equipmentName: 'MacBook Pro',
    quantity: 1,
    purpose: 'Final project development - Mobile App Development',
    duration: '3 days',
    requestDate: '2025-12-01',
    returnDate: '2025-12-04',
    status: 'pending',
    educationalPurpose: true
  },
  {
    id: 'REQ-002',
    userId: '2021-00002',
    userName: 'Maria Santos',
    userRole: 'student',
    equipmentId: 'eq21',
    equipmentName: 'VR Headset',
    quantity: 1,
    purpose: 'Research for thesis on Virtual Reality in Education',
    duration: '5 days',
    requestDate: '2025-12-01',
    returnDate: '2025-12-06',
    status: 'pending',
    educationalPurpose: true
  },
  {
    id: 'REQ-003',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq19',
    equipmentName: 'Drawing Tablet',
    quantity: 1,
    purpose: 'UI/UX Design coursework',
    duration: '1 week',
    requestDate: '2025-11-30',
    returnDate: '2025-12-07',
    status: 'pending',
    educationalPurpose: true
  },
  {
    id: 'REQ-004',
    userId: 'FAC-2020-001',
    userName: 'Dr. Robert Chen',
    userRole: 'faculty',
    equipmentId: 'eq3',
    equipmentName: '4K Projector',
    quantity: 1,
    purpose: 'Guest lecture on Machine Learning',
    duration: '1 day',
    requestDate: '2025-12-02',
    returnDate: '2025-12-02',
    status: 'pending',
    educationalPurpose: true
  },
  {
    id: 'REQ-005',
    userId: '2021-00002',
    userName: 'Maria Santos',
    userRole: 'student',
    equipmentId: 'eq18',
    equipmentName: 'Headphones',
    quantity: 2,
    purpose: 'Audio editing for multimedia project',
    duration: '2 days',
    requestDate: '2025-12-01',
    returnDate: '2025-12-03',
    status: 'pending',
    educationalPurpose: true
  },

  // APPROVED REQUESTS - already approved
  {
    id: 'REQ-006',
    userId: '2021-00002',
    userName: 'Maria Santos',
    userRole: 'student',
    equipmentId: 'eq9',
    equipmentName: 'DSLR Camera',
    quantity: 1,
    purpose: 'Documentation for thesis - Campus Study',
    duration: '1 week',
    requestDate: '2025-11-29',
    returnDate: '2025-12-06',
    status: 'approved',
    educationalPurpose: true,
    approvedBy: 'Dr. Patricia Garcia',
    approvedDate: '2025-11-29'
  },
  {
    id: 'REQ-007',
    userId: 'FAC-2020-001',
    userName: 'Dr. Robert Chen',
    userRole: 'faculty',
    equipmentId: 'eq7',
    equipmentName: 'Wireless Microphone',
    quantity: 2,
    purpose: 'Department seminar on AI Ethics',
    duration: '1 day',
    requestDate: '2025-11-28',
    returnDate: '2025-11-28',
    status: 'approved',
    educationalPurpose: true,
    approvedBy: 'Mark Wilson',
    approvedDate: '2025-11-28'
  },
  {
    id: 'REQ-008',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq2',
    equipmentName: 'Dell Laptop',
    quantity: 1,
    purpose: 'Hackathon participation - 24-hour coding event',
    duration: '2 days',
    requestDate: '2025-11-27',
    returnDate: '2025-11-29',
    status: 'approved',
    educationalPurpose: true,
    approvedBy: 'Dr. Patricia Garcia',
    approvedDate: '2025-11-27'
  },
  {
    id: 'REQ-009',
    userId: 'FAC-2019-002',
    userName: 'Prof. Ana Reyes',
    userRole: 'faculty',
    equipmentId: 'eq12',
    equipmentName: 'Portable Speaker',
    quantity: 2,
    purpose: 'Outdoor class activity - Algorithm Workshop',
    duration: '3 hours',
    requestDate: '2025-11-30',
    returnDate: '2025-11-30',
    status: 'approved',
    educationalPurpose: true,
    approvedBy: 'Mark Wilson',
    approvedDate: '2025-11-30'
  },

  // REJECTED REQUESTS
  {
    id: 'REQ-010',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq1',
    equipmentName: 'MacBook Pro',
    quantity: 5,
    purpose: 'Group project',
    duration: '2 weeks',
    requestDate: '2025-11-26',
    returnDate: '2025-12-10',
    status: 'rejected',
    educationalPurpose: true,
    rejectedBy: 'Dr. Patricia Garcia',
    rejectedDate: '2025-11-26',
    rejectionReason: 'Quantity requested exceeds limit. Please request 1-2 units.'
  },
  {
    id: 'REQ-011',
    userId: '2021-00002',
    userName: 'Maria Santos',
    userRole: 'student',
    equipmentId: 'eq27',
    equipmentName: 'Document Scanner',
    quantity: 1,
    purpose: 'Personal document scanning',
    duration: '1 day',
    requestDate: '2025-11-25',
    returnDate: '2025-11-26',
    status: 'rejected',
    educationalPurpose: false,
    rejectedBy: 'Mark Wilson',
    rejectedDate: '2025-11-25',
    rejectionReason: 'Equipment is currently under repair. Not available for borrowing.'
  },

  // COMPLETED/RETURNED REQUESTS
  {
    id: 'REQ-012',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq5',
    equipmentName: 'iPad Pro',
    quantity: 1,
    purpose: 'Digital illustration for design class',
    duration: '3 days',
    requestDate: '2025-11-20',
    returnDate: '2025-11-23',
    status: 'returned',
    educationalPurpose: true,
    approvedBy: 'Mark Wilson',
    approvedDate: '2025-11-20',
    actualReturnDate: '2025-11-23',
    condition: 'Good - No issues'
  },
  {
    id: 'REQ-013',
    userId: 'FAC-2020-001',
    userName: 'Dr. Robert Chen',
    userRole: 'faculty',
    equipmentId: 'eq4',
    equipmentName: 'Portable Projector',
    quantity: 1,
    purpose: 'Conference presentation',
    duration: '1 day',
    requestDate: '2025-11-18',
    returnDate: '2025-11-18',
    status: 'returned',
    educationalPurpose: true,
    approvedBy: 'Dr. Patricia Garcia',
    approvedDate: '2025-11-18',
    actualReturnDate: '2025-11-18',
    condition: 'Excellent'
  },
  {
    id: 'REQ-014',
    userId: '2021-00002',
    userName: 'Maria Santos',
    userRole: 'student',
    equipmentId: 'eq10',
    equipmentName: 'Action Camera',
    quantity: 1,
    purpose: 'Documentary filming for multimedia class',
    duration: '5 days',
    requestDate: '2025-11-15',
    returnDate: '2025-11-20',
    status: 'returned',
    educationalPurpose: true,
    approvedBy: 'Mark Wilson',
    approvedDate: '2025-11-15',
    actualReturnDate: '2025-11-21',
    condition: 'Good - Returned 1 day late',
    lateFee: 50
  },

  // OVERDUE REQUESTS
  {
    id: 'REQ-015',
    userId: '2021-00001',
    userName: 'Juan Dela Cruz',
    userRole: 'student',
    equipmentId: 'eq6',
    equipmentName: 'Android Tablet',
    quantity: 1,
    purpose: 'App testing and debugging',
    duration: '5 days',
    requestDate: '2025-11-22',
    returnDate: '2025-11-27',
    status: 'overdue',
    educationalPurpose: true,
    approvedBy: 'Mark Wilson',
    approvedDate: '2025-11-22',
    daysOverdue: 5
  },
];

